apiVersion: v2
name: maybe
description: A fullyopen-source OS for your personal finances
type: application
version: 0.1.4
appVersion: "0.1.0-alpha.9"
dependencies:
  - name: postgresql
    version: "15.5.14"
    repository: "https://charts.bitnami.com/bitnami"