---
remote: origin
target-branch: main
chart-dirs:
  - ./
chart-repos:
  - maybe-helm=ghcr.io/channel-42/maybe-helm
check-version-increment: false
validate-maintainers: false
exclude-deprecated: true
excluded-charts: []