---
name: "Lint and Test Chart"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/artifacthub/ah:v1.20.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ah lint
        working-directory: ./
        run: ah lint

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml