name: Renovate

on:
  schedule:
    - cron: "0 7,10,16,22 * * *"

jobs:
  renovate:
    permissions:
      contents: read
      issues: read
      pull-requests: write
      repository-projects: read
      statuses: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: ./.github/configs/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}